server:
  servlet:
    context-path: /accounts
  port: 5502

spring:
  datasource:
    url: {$DATABASE_URL}
    username: {$USERNAME}
    password: {PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true